#!/usr/bin/env tsx

import { execSync } from "node:child_process";
import fs from "node:fs";
import { processMarkdownFiles } from "./generate-readme.js";

function run(cmd: string, options?: { silent?: boolean }): void {
  execSync(cmd, {
    stdio: options?.silent ? "pipe" : "inherit",
    encoding: "utf-8",
  });
}

const GENERATED_WARNING = `<!--
  ⚠️ DO NOT EDIT THIS FILE DIRECTLY
  Edit src/README.md instead - this file is auto-generated by pnpm build
-->

`;

async function main(): Promise<void> {
  console.log("📖 Building README.md...");
  fs.copyFileSync("src/README.md", "README.md");
  const content = fs.readFileSync("README.md", "utf-8");
  fs.writeFileSync("README.md", GENERATED_WARNING + content);
  await processMarkdownFiles(["README.md"]);
  run("pnpm exec markdownlint --fix README.md", { silent: true });
  console.log("   ✅ README.md updated");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
